name: MAUI Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest   # snel en stabiel

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Herstel afhankelijkheden (alleen testproject)
        run: dotnet restore ./Grocery.Tests/Grocery.Tests.csproj

      - name: Voer alleen .NET unit tests uit
        run: dotnet test ./Grocery.Tests/Grocery.Tests.csproj --framework net8.0 --configuration Release --verbosity normal



