name: MAUI Build

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Installeer MAUI workloads (android)
        run: dotnet workload install maui-android

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Bouw de applicatie
        run: dotnet build --configuration Release --no-restore
