name: MAUI Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest   # snel en stabiel

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Herstel afhankelijkheden (negeer workloads)
        run: dotnet restore --ignore-failed-sources

      - name: Voer alleen .NET unit tests uit
        run: dotnet test --framework net8.0 --no-restore --verbosity normal


