name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest   # sneller en goedkoper dan macOS

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Voer alleen .NET unit tests uit (geen iOS/Android)
        run: dotnet test --framework net8.0 --configuration Release --verbosity normal

